### ISSUE TITLE
Uncaught TypeError: stickybits is not a function

### ISSUE THREAD

**Issue by piersolenski** [horizon0708/react-scroll-jacker#2]
Getting the following error on a fresh install of Create React App:

```
Uncaught TypeError: stickybits is not a function
    at ScrollJacker../node_modules/react-scroll-jacker/lib/reactScrollJacker.js.ScrollJacker.componentDidMount (reactScrollJacker.js:55)
```

**Comment by horizon0708** [comment]
I am sorry for the late response, I will definitely take a look at this today. It shouldn't be too hard to fix.

**Comment by horizon0708** [comment]
Hiya, I've fixed it now. Sorry for late fix :(
