### ISSUE TITLE
Why cant i cant this to work

### ISSUE THREAD

**Issue by nojdavid** [horizon0708/react-scroll-jacker#3]
can i not use scroll jacker with sections? Do they have to be react elements? I feel that it should work

**Comment by horizon0708** [comment]
This component injects props to the child elements, which I believe is not possible to do for normal html elements. You could, however, easily make those sections into a react element.

**Comment by noudadrichem** [comment]
I agree on this, it would be nice to place just HTML elements inside the react scrollpackage. Or to be able to grab some short of shorthand to create the element.

**Comment by rubensjp** [comment]
I am using react element but I can only see the top most element to render. I cloned the repo and the same thing happens.

**Comment by mbodge** [comment]
Same issue here. Only the first element renders.
